name: soul-app

services:
  - name: soul-service
    type: web
    build:
      # Install dependencies
      commands:
        - apt-get update && apt-get install -y gcc python3 python3-pip
        - pip install -r requirements.txt
        - gcc soul.c -o soul_c.out  # Compile the C file
    run:
      command: python3 soul.py  # Run the Python script
    ports:
      - 8080  # Change this if needed
